CREATE TABLE `groups` (
	id INT AUTO_INCREMENT PRIMARY KEY,
	owner_id INT NOT NULL,
	name VARCHAR(255),
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE CASCADE
);
