CREATE TABLE group_posts (
	id INT AUTO_INCREMENT PRIMARY KEY,
	group_id INT NOT NULL,
	author_id INT NOT NULL,
	context TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(group_id) REFERENCES `groups`(id) ON DELETE CASCADE,
	FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE
);

